plugins {
    id "io.micronaut.build.internal.jaxrs-module"
}

dependencies {
    implementation projects.micronautJaxrsCommon
    implementation(mn.micronaut.http)
    implementation(mn.micronaut.core.processor)
    implementation(libs.micronaut.sourcegen.annotations)
    implementation(libs.micronaut.sourcegen.generator)
    implementation(libs.micronaut.sourcegen.generator.java)
    implementation(libs.managed.jaxrs.api)

    testAnnotationProcessor(mnValidation.micronaut.validation.processor)

    testImplementation(mnValidation.micronaut.validation.processor)
    testImplementation(mn.micronaut.http.validation)
    testImplementation(mn.micronaut.http.server)
    testImplementation(mn.micronaut.inject.java.test)
    testImplementation(mnValidation.micronaut.validation)
    testImplementation(mn.micronaut.http.client)
}
