[versions]
managed-jaxrs-api = "3.1.0"
micronaut = "5.0.0-M6"
micronaut-security = "5.0.0-M1"
micronaut-serde = "3.0.0-M6"
micronaut-logging = "1.7.1"
micronaut-servlet = "6.0.0-M1"
micronaut-validation = "5.0.0-M1"
micronaut-reactor = "4.0.0-M1"
jakarta-jaxrs-tck = "4.0.1"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = 'micronaut-reactor' }
micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-servlet = { module = "io.micronaut.servlet:micronaut-servlet-bom", version.ref = "micronaut-servlet" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-jaxrs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "managed-jaxrs-api" }

junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine" }
jakarta-jaxrs-tck-tests = { module = 'jakarta.ws.rs:jakarta-restful-ws-tck', version.ref = "jakarta-jaxrs-tck" }
